apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: docker-compose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: docker-compose-multi-service-php:latest
          imagePullPolicy: Never

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret

          ports:
            - containerPort: 9000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: docker-compose
spec:
  selector:
    app: php
  ports:
    - port: 9000
      targetPort: 9000
