name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat <<EOF > .env
          DB_HOST=postgres
          DB_PORT=5432
          DB_NAME=devopsdb
          DB_USER=andre
          DB_PASSWORD=password
          EOF

      - name: Build Docker Images
        run: docker compose build

      - name: Start Containers
        run: docker compose up -d

      - name: Wait for Services
        run: sleep 20

      - name: Check Running Containers
        run: docker ps

      - name: Test Web Application
        run: curl --fail http://localhost:8080

      - name: Stop Containers
        if: always()
        run: docker compose down
